### ISSUE TITLE
Failed to upload the report

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.Codecov#18]
My Cake addin build keeps failing (as you can see [here](https://ci.appveyor.com/project/cakecontrib/cake-email-common/build/0.2.0%2B0.build.11), [here](https://ci.appveyor.com/project/cakecontrib/cake-email-common/build/0.2.0%2B0.build.10) and [here](https://ci.appveyor.com/project/cakecontrib/cake-email-common/build/0.2.0%2B0.build.9)) with the following error:

```
              _____          _
             / ____|        | |
            | |     ___   __| | ___  ___ _____   __
            | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
            | |___| (_) | (_| |  __/ (_| (_) \ V /
             \_____\___/ \____|\___|\___\___/ \_/
                                         exe-1.0.3
            
2018-03-08 21:29:08 [Information] AppVeyor detected.
2018-03-08 21:29:08 [Information] Git detected.
2018-03-08 21:29:08 [Information] Project root: C:\projects\cake-email-common
2018-03-08 21:29:08 [Information] Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
2018-03-08 21:29:08 [Information] Reading reports.
2018-03-08 21:29:08 [Information] BuildArtifacts/TestCoverage/OpenCover.xml
2018-03-08 21:29:08 [Information] Uploading Reports.
2018-03-08 21:29:09 [Information] url: https://codecov.io
2018-03-08 21:29:10 [Information] query: https://codecov.io/upload/v4?branch=master&commit=c5b45acda9c64af385308d38a3501d1898bbab14&build=uhf6jhk5uh637e97&tag=&pr=&name=&flags=&slug=cake-contrib%2FCake.Email.Common&token=&package=exe-1.0.3&build_url=&yaml=&job=cakecontrib%2Fcake-email-common%2F0.2.0%2B0.build.11&service=appveyor
2018-03-08 21:29:10 [Information] Pinging Codecov
2018-03-08 21:29:18 [Fatal] Failed to upload the report.
   at Codecov.Upload.Uploads.Uploader() in C:\Users\larz\github\codecov-exe\Source\Codecov\Upload\Uploads.cs:line 34
   at Codecov.Program.UploadFacade.Uploader() in C:\Users\larz\github\codecov-exe\Source\Codecov\Program\UploadFacade.cs:line 119
   at Codecov.Program.Run.Runner(IEnumerable`1 args) in C:\Users\larz\github\codecov-exe\Source\Codecov\Program\Run.cs:line 20
Cake.exe : An error occurred when executing task 'Upload-Codecov-Report'.
At C:\projects\cake-email-common\build.ps1:235 char:1
+ &$CAKE_EXE $cakeArguments
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (An error occurr...odecov-Report'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Codecov: Process returned an error (exit code 1).
```
Any help investigating this issue would be appreciated.

**Comment by Jericho** [comment]
I'm starting to suspect the issue might me with the codecov service. It would be great if your addin was able to display a more descriptive error message.

**Comment by gep13** [comment]
@Jericho I have been seeing the same problem across some of my repos, so it isn't just you :-(

I am going to turn this off by default in Cake.Recipe until we can figure out what is going on.

**Comment by AdmiringWorm** [comment]
This error isn't from the addin itself, but rather the [Codecov](https://github.com/codecov/codecov-exe) tool. Could you please open a issue over there instead.

Thanks.

**Comment by gep13** [comment]
We have been discussing this here:

https://github.com/codecov/codecov-exe/issues/35#issuecomment-371755901

**Comment by gep13** [comment]
@AdmiringWorm is there anything "special" that has to be done to setup the projects on codecov.io?  I thought it "just" happened.

**Comment by AdmiringWorm** [comment]
@gep13 I believe this issue, and that one may be two different issues. Of course I could be wrong in that case.

> @AdmiringWorm is there anything "special" that has to be done to setup the projects on codecov.io? I thought it "just" happened.

No it shouldn't be, it have always been created automatically whenever I used it. Let me try looking at the docs to see if anything have changed.

**Comment by AdmiringWorm** [comment]
@gep13 nope, shouldn't need to do anything.
As long as a user have read access to the repository it should be automatically created.

**Comment by gep13** [comment]
@AdmiringWorm oh, you are right, they are different error messages.

**Comment by gep13** [comment]
@AdmiringWorm yip, that should certainly be the case.

**Comment by AdmiringWorm** [comment]
I believe this was fixed upstream some time ago, as such I'll be closing this issue now.
